#!/usr/bin/env python3
import sys
import re
import os

def get_arx_byte(i: int, k1: int, k2: int, k3: int, k4: int) -> int:
    v0 = (i ^ k1) & 0xFFFFFFFF
    v1 = (v0 + k2) & 0xFFFFFFFF
    rot = (k3 + i) & 31
    v2 = ((v1 << rot) | (v1 >> (32 - rot))) & 0xFFFFFFFF
    v3 = v2 ^ k4
    return v3 & 0xFF

def main():
    xor_header_path = "Loader/xor_strings.h"
    raw_patterns_path = "Loader/aob_patterns_raw.c"
    output_patterns_path = "Loader/aob_patterns.c"

    # Step 1: Read keys from xor_strings.h
    if not os.path.exists(xor_header_path):
        print(f"Error: {xor_header_path} not found. Run gen_xor_strings_dynamic.py first.")
        sys.exit(1)

    with open(xor_header_path, 'r', encoding='utf-8') as f:
        keys_content = f.read()

    k1_match = re.search(r'#define\s+SERAPH_KEY1\s+(\d+)u?', keys_content)
    k2_match = re.search(r'#define\s+SERAPH_KEY2\s+(\d+)u?', keys_content)
    k3_match = re.search(r'#define\s+SERAPH_KEY3\s+(\d+)u?', keys_content)
    k4_match = re.search(r'#define\s+SERAPH_KEY4\s+(\d+)u?', keys_content)

    if not (k1_match and k2_match and k3_match and k4_match):
        print("Error: Could not parse SERAPH_KEY1..4 from xor_strings.h")
        sys.exit(1)

    k1 = int(k1_match.group(1))
    k2 = int(k2_match.group(1))
    k3 = int(k3_match.group(1))
    k4 = int(k4_match.group(1))

    print(f"Parsed keys: K1={k1}, K2={k2}, K3={k3}, K4={k4}")

    # Step 2: Read raw patterns
    if not os.path.exists(raw_patterns_path):
        print(f"Error: {raw_patterns_path} not found.")
        sys.exit(1)

    with open(raw_patterns_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Step 3: Find and encrypt all UINT8 arrays
    # Regex matches: const UINT8 name[] = { ... }; or static const UINT8 name[] = { ... };
    array_pattern = re.compile(r'((?:static\s+)?const\s+UINT8\s+(\w+)\[\]\s*=\s*\{)([\s\S]*?)(\};)')

    def encrypt_array(match):
        prefix = match.group(1)
        name = match.group(2)
        body = match.group(3)
        suffix = match.group(4)

        # Extract all hex and decimal values from the body
        # Hex: 0xXX, Dec: XX
        bytes_strs = re.findall(r'0x[0-9a-fA-F]+|\b\d+\b', body)
        raw_bytes = []
        for bs in bytes_strs:
            if bs.startswith('0x') or bs.startswith('0X'):
                raw_bytes.append(int(bs, 16))
            else:
                raw_bytes.append(int(bs, 10))

        # Encrypt each byte
        encrypted_bytes = []
        for i, b in enumerate(raw_bytes):
            kb = get_arx_byte(i, k1, k2, k3, k4)
            encrypted_bytes.append(b ^ kb)

        # Format encrypted array
        formatted_bytes = ", ".join(f"0x{eb:02X}" for eb in encrypted_bytes)
        print(f"Encrypted AOB: {name} (len={len(raw_bytes)})")
        return f"{prefix} {formatted_bytes} {suffix}"

    obfuscated_content = array_pattern.sub(encrypt_array, content)

    # Step 4: Write output to aob_patterns.c
    header_comment = """/* Auto-generated encrypted AOB patterns file.
   Generated by encrypt_aobs.py. DO NOT EDIT MANUALLY. */\n\n"""

    # Replace the "DO NOT compile directly" comment from the raw file
    raw_comment_pattern = re.compile(r'/\*[\s\S]*?\*/')
    obfuscated_content = raw_comment_pattern.sub("", obfuscated_content, count=1)

    with open(output_patterns_path, 'w', encoding='utf-8') as f:
        f.write(header_comment + obfuscated_content.strip() + "\n")

    print(f"Successfully generated encrypted {output_patterns_path}")

if __name__ == "__main__":
    main()
